name: NanoServer MSVC

on:
  workflow_dispatch:

env:
  VS_BOOTSTRAP_VERSION: 17.13.6

jobs:
  build-and-push:
    runs-on: windows-2022

    env:
      entry: pwsh.exe
      cmd: -NoLogo -NoProfile -ExecutionPolicy Bypass

    outputs:
      image_tagged: ${{ steps.vars.outputs.image_tagged }}

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set image tag
      id: vars
      run: |
        $repo = $env:GITHUB_REPOSITORY.ToLower()
        $imageBase = "ghcr.io/$repo"
        $taggedImage = "${imageBase}:${env:VS_BOOTSTRAP_VERSION}"
        "image_tagged=$taggedImage" >> $env:GITHUB_OUTPUT

    - name: Log in to GHCR
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $env:GITHUB_ACTOR --password-stdin

    - name: Build Image
      run: |
        docker build `
          --isolation process `
          --build-arg "IMPL_COMPRESSION_OPTIONS=-T0 --ultra" `
          --build-arg "IMPL_COMPRESSION_LEVEL=22" `
          --build-arg "VS_BOOTSTRAP_VERSION=$env:VS_BOOTSTRAP_VERSION" `
          -t "${{ steps.vars.outputs.image_tagged }}" .

    - name: Push Image
      run: |
        docker push "${{ steps.vars.outputs.image_tagged }}"

  run-nano-container:
    needs: build-and-push
    runs-on: windows-2022

    defaults:
      run:
        shell: pwsh

    steps:
    - name: Log in to GHCR
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u $env:GITHUB_ACTOR --password-stdin

    - name: Pull Image
      run: docker pull "${{ needs.build-and-push.outputs.image_tagged }}"

    - name: Run Container
      run: docker run --entrypoint ${{ env.entry }} --isolation process -di --name orphan "${{ needs.build-and-push.outputs.image_tagged }}" ${{ env.cmd }}

    - name: Inspect Container
      run: docker inspect orphan

    - name: Container – Unpack Packages
      run: docker exec orphan ${{ env.entry }} ${{ env.cmd }} C:\unpack.ps1

    - name: Container – Configure CMake Project
      run: docker exec orphan ${{ env.entry }} ${{ env.cmd }} -Command cmake --preset configure-msvc-winsdk

    - name: Container – Build Sample Project
      run: docker exec orphan ${{ env.entry }} ${{ env.cmd }} -Command cmake --build --preset build-msvc-winsdk --config Release -- -j 14

    - name: Container – Test Sample Project
      run: docker exec -w "C:\sample\tests\build-ct\src" orphan ${{ env.entry }} ${{ env.cmd }} -Command ctest -C Release --stop-on-failure --verbose